### ISSUE TITLE
No logs in OPENFIRE_LOG_DIR and error "No Log4j 2 configuration file found"

### ISSUE THREAD

**Issue by bseiller** [gizmotronic/docker-openfire#3]
We are currently trying to debug a login/connection issue of an automated XMPP client (Jenkins) with our dockerized Openfire server running with your image "gizmotronic/openfire" and default folders.

The problem is there aren't any logs apart from `docker [CONTAINER_NAME] logs`, neither in the admin console
![no_logs](https://user-images.githubusercontent.com/10873070/61462261-9d2f4f00-a972-11e9-8490-a11d318d6bb3.png)
nor under `/usr/share/openfire/logs` or under `/var/log/openfire/`

And the docker logs of the instance contain the following error
`ERROR StatusLogger No Log4j 2 configuration file found. Using default configuration (logging only errors to the console), or user programmatically provided configurations. Set system property 'log4j2.debug' to show Log4j 2 internal initialization logging. See https://logging.apache.org/log4j/2.x/manual/configuration.html for instructions on how to configure Log4j 2`

Can this be a result of the function `rewire_openfire()` in entrypoint.sh?
Also, there are actually 2 log4j2.xml in the container
`/usr/share/openfire/lib/log4j2.xml` which symlinks to `/etc/openfire/log4j2.xml`
`/var/lib/openfire/conf/log4j2.xml`

Which config do we need to change to get the logs in the admin console? 
Are there any other changes we can make to get more than the error-logs?
Which log4j2.xml is the correct one to change if we need more details?
Any help is really appreciated!

**Comment by gizmotronic** [comment]
This is related to [OF-1676](https://issues.igniterealtime.org/browse/OF-1676). I've updated the entrypoint.sh script to account for the changes to Openfire 4.3 and later. Images should appear on Docker Hub shortly.

To configure log4j, you should include a `log4j2.xml` configuration file in the Openfire configuration volume that you've created for your container. Note that this is a change from Openfire 4.2.x and earlier, which used a `log4j.xml` file instead.

**Comment by bseiller** [comment]
Thanks for the fast reply - by now I had found a workaround for the original problem (patched the Jenkins plugin to write some meaningful errors in its log) but once we need the openfire logs again, we'll update to version 4.4.0.
