### ISSUE TITLE
Turn off update 

### ISSUE THREAD

**Issue by rfatolahzade** [gizmotronic/docker-openfire#4]
Hello
How can i disable internet access and set update off?

**Comment by gizmotronic** [comment]
You should control network access using either your container management platform or an external firewall. For example, if you're running this in a Kubernetes cluster, you should apply the appropriate pod security policy. The specifics of how you would do this are outside of the scope of this project.

I'm not sure what you mean by "set update off", but assuming that you mean the news feed update, I'm not aware of a way to limit that. You may be able to find an answer over at the [Openfire community](https://discourse.igniterealtime.org) site.
